In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1228, 9243, 7802, 7487],
 [1228, 9243, 7802, 2476],
 [1228, 3312, 7802, 9569],
 [8502, 4789, 1946, 2112, 5331],
 [8502, 4789, 1946, 2112, 5472],
 [4492, 1228, 3846, 7802, 7725],
 [7984, 2872, 6932, 2112]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1228 9243 7802 7487]
 [   0    0    0    0 1228 9243 7802 2476]
 [   0    0    0    0 1228 3312 7802 9569]
 [   0    0    0 8502 4789 1946 2112 5331]
 [   0    0    0 8502 4789 1946 2112 5472]
 [   0    0    0 4492 1228 3846 7802 7725]
 [   0    0    0    0 7984 2872 6932 2112]]


In [9]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\user\Desktop\deep learning\ANN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 677ms/step


array([[[ 0.00892783, -0.04930427, -0.0091251 , -0.00520775,
         -0.02939571, -0.02028574,  0.04675386,  0.0369481 ,
          0.01670793,  0.00256276],
        [ 0.00892783, -0.04930427, -0.0091251 , -0.00520775,
         -0.02939571, -0.02028574,  0.04675386,  0.0369481 ,
          0.01670793,  0.00256276],
        [ 0.00892783, -0.04930427, -0.0091251 , -0.00520775,
         -0.02939571, -0.02028574,  0.04675386,  0.0369481 ,
          0.01670793,  0.00256276],
        [ 0.00892783, -0.04930427, -0.0091251 , -0.00520775,
         -0.02939571, -0.02028574,  0.04675386,  0.0369481 ,
          0.01670793,  0.00256276],
        [ 0.03048212, -0.03324316, -0.01546575,  0.03753266,
          0.04504721,  0.03686973,  0.02074584,  0.03720221,
          0.01463187,  0.01630472],
        [-0.00591601, -0.03702486,  0.04992903, -0.04693549,
         -0.04324987, -0.02498212, -0.03346658,  0.0267548 ,
         -0.02055106, -0.02779654],
        [ 0.01533927, -0.02321961,  0.04418978,  0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 1228, 9243, 7802, 7487], dtype=int32)

In [15]:

model.predict(np.array([embedded_docs[0]]))  # Add batch dimension


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step


array([[[ 0.00892783, -0.04930427, -0.0091251 , -0.00520775,
         -0.02939571, -0.02028574,  0.04675386,  0.0369481 ,
          0.01670793,  0.00256276],
        [ 0.00892783, -0.04930427, -0.0091251 , -0.00520775,
         -0.02939571, -0.02028574,  0.04675386,  0.0369481 ,
          0.01670793,  0.00256276],
        [ 0.00892783, -0.04930427, -0.0091251 , -0.00520775,
         -0.02939571, -0.02028574,  0.04675386,  0.0369481 ,
          0.01670793,  0.00256276],
        [ 0.00892783, -0.04930427, -0.0091251 , -0.00520775,
         -0.02939571, -0.02028574,  0.04675386,  0.0369481 ,
          0.01670793,  0.00256276],
        [ 0.03048212, -0.03324316, -0.01546575,  0.03753266,
          0.04504721,  0.03686973,  0.02074584,  0.03720221,
          0.01463187,  0.01630472],
        [-0.00591601, -0.03702486,  0.04992903, -0.04693549,
         -0.04324987, -0.02498212, -0.03346658,  0.0267548 ,
         -0.02055106, -0.02779654],
        [ 0.01533927, -0.02321961,  0.04418978,  0.0